version: '3'
services:
  node:
    build:
      context: .
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
    - ./:/usr/src/app

    command: sh -c "cd react-task && npm start"
    ports:
    - "8080:8080"
  json-server:
    container_name: json-server-dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JSON_SERVER_PORT=5000
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - 5000:5000